"""empty message

Revision ID: 00de4db629e4
Revises: bbaa436e24f5
Create Date: 2024-02-18 13:35:08.254887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00de4db629e4'
down_revision: Union[str, None] = 'bbaa436e24f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings_events', sa.Column('hour_start', sa.Integer(), nullable=False))
    op.add_column('meetings_events', sa.Column('minutes_start', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings_events', 'minutes_start')
    op.drop_column('meetings_events', 'hour_start')
    # ### end Alembic commands ###
