"""empty message

Revision ID: 1624b3068b06
Revises: fc6110cf7783
Create Date: 2024-02-08 12:51:32.196546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1624b3068b06'
down_revision: Union[str, None] = 'fc6110cf7783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sport_interest_id', sa.Integer(), nullable=False),
    sa.Column('meeting_interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_interest_id'], ['meetings_interests.id'], ),
    sa.ForeignKeyConstraint(['sport_interest_id'], ['sports_interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sport_interest_id', 'meeting_interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_interests')
    # ### end Alembic commands ###
