"""empty message

Revision ID: 256144e49bef
Revises: f222867cf37f
Create Date: 2024-02-11 11:49:06.926846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256144e49bef'
down_revision: Union[str, None] = 'f222867cf37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings_events_interests', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meetings_events_interests', 'meetings_events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings_events_interests', type_='foreignkey')
    op.drop_column('meetings_events_interests', 'event_id')
    # ### end Alembic commands ###
