"""empty message

Revision ID: 2acf39965e6f
Revises: 
Create Date: 2024-02-09 17:37:58.305065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acf39965e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('patronymic_name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.String(length=64), nullable=True),
    sa.Column('about', sa.String(length=1024), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travels_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('location_start', sa.String(length=64), nullable=True),
    sa.Column('location_end', sa.String(length=64), nullable=True),
    sa.Column('date_start', sa.String(length=64), nullable=False),
    sa.Column('date_end', sa.String(length=64), nullable=True),
    sa.Column('header', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('travel_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('promo_type', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('preferred_gender', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_by')
    )
    op.create_table('sports_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.Column('header', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('promo_type', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('preferred_gender', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_by')
    )
    op.create_table('sports_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('interest_ru', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interest'),
    sa.UniqueConstraint('interest_ru')
    )
    op.create_table('meetings_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.Column('header', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('promo_type', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('preferred_gender', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_by')
    )
    op.create_table('meetings_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('interest_ru', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interest'),
    sa.UniqueConstraint('interest_ru')
    )
    op.create_table('code_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_meetings_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['interest'], ['meetings_interests.interest'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interest')
    )
    op.create_table('users_sports_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['interest'], ['sports_interests.interest'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interest')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_challenge')
    op.drop_table('meetings_interests')
    op.drop_table('meetings_events')
    op.drop_table('sports_interests')
    op.drop_table('sports_events')
    op.drop_table('travels_events')
    op.drop_table('users_sports_interests')
    op.drop_table('users_meetings_interests')
    op.drop_table('users')
    # ### end Alembic commands ###
