"""empty message

Revision ID: 3fa5bcb6979a
Revises: d02d1b913d42
Create Date: 2024-02-06 20:14:16.214746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa5bcb6979a'
down_revision: Union[str, None] = 'd02d1b913d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_interests')
    op.drop_table('meeting_interests')
    # ### end Alembic commands ###
