"""empty message

Revision ID: d02d1b913d42
Revises: 62cffaab5796
Create Date: 2024-02-04 16:15:14.315849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02d1b913d42'
down_revision: Union[str, None] = '62cffaab5796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_challenge', sa.Column('attempt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_challenge', 'attempt')
    # ### end Alembic commands ###
