"""empty message

Revision ID: de9ac78f031d
Revises: 3fa5bcb6979a
Create Date: 2024-02-06 20:59:24.299118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9ac78f031d'
down_revision: Union[str, None] = '3fa5bcb6979a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_interests', sa.Column('interest_ru', sa.String(), nullable=True))
    op.add_column('sport_interests', sa.Column('interest_ru', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_interests', 'interest_ru')
    op.drop_column('meeting_interests', 'interest_ru')
    # ### end Alembic commands ###
