"""empty message

Revision ID: f222867cf37f
Revises: 67117a3b4a27
Create Date: 2024-02-11 11:42:13.072682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f222867cf37f'
down_revision: Union[str, None] = '67117a3b4a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings_events_interests',
    sa.Column('interest', sa.String(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['interest'], ['meetings_interests.interest'], ),
    sa.PrimaryKeyConstraint('interest')
    )
    op.create_unique_constraint(None, 'meetings_events', ['id'])
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.drop_constraint(None, 'meetings_events', type_='unique')
    op.drop_table('meetings_events_interests')
    # ### end Alembic commands ###
